### ISSUE TITLE
大佬，比赛看不了

### ISSUE THREAD

**Issue by wweggplant** [chenyaoyi88/hupumoyu-assistant#3]
![image](https://user-images.githubusercontent.com/4509523/197092919-eeada838-7760-4a20-b5a3-e056a588bc10.png)

**Comment by chenyaoyi88** [comment]
卸载重新安装或者关掉vscode重新打开试试看？我自己也看着直播逛着步行街呢

**Comment by wweggplant** [comment]
> 卸载重新安装或者关掉vscode重新打开试试看？我自己也看着直播逛着步行街呢

卸载了也不行呢

**Comment by chenyaoyi88** [comment]
> > 卸载重新安装或者关掉vscode重新打开试试看？我自己也看着直播逛着步行街呢
> 
> 卸载了也不行呢

刚更新了版本，看看修复没。

**Comment by wweggplant** [comment]
> > > 卸载重新安装或者关掉vscode重新打开试试看？我自己也看着直播逛着步行街呢
> > 
> > 
> > 卸载了也不行呢
> 
> 刚更新了版本，看看修复没。

可以了，大佬牛逼
