### ISSUE TITLE
看比赛的列表获取错误?

### ISSUE THREAD

**Issue by CatAndMe** [chenyaoyi88/hupumoyu-assistant#4]
Extension chenyaoyi888168.hupumoyu-assistant has provided an invalid tree item.

**Comment by ehzuf** [comment]
同样的问题

**Comment by chenyaoyi88** [comment]
> Extension chenyaoyi888168.hupumoyu-assistant has provided an invalid tree item.

会不会是 vscode 的版本太低的原因？最低支持的是 1.64.0

**Comment by chenyaoyi88** [comment]
> 同样的问题

会不会是 vscode 的版本太低的原因？最低支持的是 1.64.0

**Comment by ehzuf** [comment]
> > 同样的问题
> 
> 会不会是 vscode 的版本太低的原因？最低支持的是 1.64.0

最新的版本，Version: 1.72.2 (Universal)，MacBook Pro Apple M1 Pro，插件卸载重装过，还是存在这个问题。
看步行街之类的论坛内容是正常的，只有比赛不能看。

**Comment by ehzuf** [comment]
查到一个类似的issue，不确定是不是因为这个

https://github.com/microsoft/vscode/issues/157273

**Comment by panta1209** [comment]
我也碰到了同样的问题，MacBook Pro Apple M1 Pro，版本1.73.0

**Comment by chenyaoyi88** [comment]
> 我也碰到了同样的问题，MacBook Pro Apple M1 Pro，版本1.73.0

刚更新了版本，看看修复没。

**Comment by chenyaoyi88** [comment]
> 查到一个类似的issue，不确定是不是因为这个
> 
> [microsoft/vscode#157273](https://github.com/microsoft/vscode/issues/157273)

刚更新了版本，看看修复没。

**Comment by chenyaoyi88** [comment]
> Extension chenyaoyi888168.hupumoyu-assistant has provided an invalid tree item.

刚更新了版本，看看修复没。

**Comment by CatAndMe** [comment]
好了

**Comment by ehzuf** [comment]
> 

可以了，谢谢

**Comment by panta1209** [comment]
可以了，谢谢
