### ISSUE TITLE
论坛打不开了

### ISSUE THREAD

**Issue by AlanNewGxd** [chenyaoyi88/hupumoyu-assistant#5]
论坛打不开了

**Comment by chenyaoyi88** [comment]
> 论坛打不开了

把 vscode 关掉重开试试，有时候开了 VPN 之后再关掉，请求就一直失败了

**Comment by AlanNewGxd** [comment]
> 把 vscode 关掉重开试试，有时候开了 VPN 之后再关掉，请求就一直失败了
不好使，试了很多次了，之前都是好的，我电脑没有vpn

**Comment by AlanNewGxd** [comment]
> > 论坛打不开了
> 
> 把 vscode 关掉重开试试，有时候开了 VPN 之后再关掉，请求就一直失败了

报错：获取论坛板块数据失败
