### ISSUE TITLE
无法查看比赛数据

### ISSUE THREAD

**Issue by sunyangcheng** [chenyaoyi88/hupumoyu-assistant#6]
当比赛还在进行中时，点击查看数据是正常的
比赛结束后，点击数据，显示空白
![image](https://user-images.githubusercontent.com/38790278/212250947-14a9f0b3-1939-45cd-83fa-e8497046bb32.png)

**Comment by chenyaoyi88** [comment]
> 当比赛还在进行中时，点击查看数据是正常的 比赛结束后，点击数据，显示空白 ![image](https://user-images.githubusercontent.com/38790278/212250947-14a9f0b3-1939-45cd-83fa-e8497046bb32.png)

其实之前也发现了，虎扑在比赛结束后就把之前的数据统计页做了重定向，晚点有时间我换成直接请求手机端的数据接口就好了。
